### ISSUE TITLE
High value for JOINT_ANGLE_DEADZONE

### ISSUE THREAD

**Issue by mduffor** [FRC5411/Lofty-2023#27]
https://github.com/FRC5411/Lofty-2023/blob/cd5b69fb926bb0f2de8c7efeefe3e5a42fe9e3b9/src/main/java/frc/robot/subsystems/Arm.java#L244

Your JOINT_COORDINATE_DEADZONE is currently set to 0 which is probably too small a deadzone since it doesn't do anything. Conversely, JOINT_ANGLE_DEADZONE is set to 20, which is probably too large a deadzone as it will cause the command to give up when still quite a distance from the target.  That probably explains why isAtTarget is commented out and not used in 2 of the 3 places it appears in the code.

**Comment by RDc12Programming** [comment]
actually, JOINT_ANGLE_DEADZONE is the deadzone for moving the second stage when moving to or from idle, so it being large just makes the second stage start moving before the first stage arrives fully at target. the actual "give up" threshold is defined in Arm.java with the PID instantiations. "isAtTarget" was removed because those commands were restructured, they should not end until interrupted. this is intentional.

**Comment by mduffor** [comment]
Then ideally name the constant to make this more clear.  JOINT_ANGLE_STAGE_2_TRIGGER or somesuch.
